# Generated by Django 5.0.7 on 2024-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_category_hashtag_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='journal.hashtag'),
        ),
    ]
