# Generated by Django 5.0.7 on 2024-07-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_publication_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='read_time',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='время чтения'),
        ),
    ]
