# Generated by Django 5.0.7 on 2024-07-29 13:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
